apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: angular
  name: angular
  namespace: devops-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angular
    spec:
      terminationGracePeriodSeconds: 31
      volumes:
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: secret-nginx
      - name: configmap-volume
        configMap:
          defaultMode: 420
          name: nginx
      containers:
      - image: docker.io/01521433811/frontend-project:TAG_NUMBER
        name: angular-frontend
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/pabel
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume

status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: angular
  name: angular
  namespace: devops-test
spec:
  type: LoadBalancer
  selector:
    app: angular
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30504
    name: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30343
status:
  loadBalancer: {}
